plugins:
  - rubocop-performance
  - rubocop-capybara

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 180

Metrics/BlockLength:
  Exclude:
    - db/migrate/*.rb
    - db/schema.rb
    - config/environments/*.rb
    - spec/**/*

Metrics/MethodLength:
  Exclude:
    - db/migrate/*.rb

Metrics/AbcSize:
  Exclude:
    - db/migrate/20250329191013_create_active_storage_tables.active_storage.rb