services:
  db:
    image: postgres:17
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "password"
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    ports: 
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USERNAME: postgres
      RAILS_ENV: production
      RAILS_MASTER_KEY: dd7c5333247ba4989e7a4690f53546fa
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app

volumes:
  postgresql_data: {}