version: "1.0.0"
services:
  db:
    image: postgres:17
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ""
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    ports: 
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USERNAME: postgres

volumes:
  postgresql_data: {}