service: resolute-fitness
# Name of the container image.
image: jmalkin/resolute-fitness

# Deploy to these servers.
servers:
  web:
    hosts:
      - 159.65.60.245
    options:
      memory: 512m

registry:
  username: jmalkin
  password:
    - KAMAL_REGISTRY_PASSWORD

proxy:
  ssl: true 
  hosts:
    - resolutefitness.studio
    - www.resolutefitness.studio
  app_port: 3000

env:
  clear:
    DB_HOST: resolute-fitness-db
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD

volumes:
  - rails-storage:/resolute-fitness/storage
  - log:/resolute-fitness/log

builder:
  arch: amd64

accessories:
  db:
    image: postgres:17
    host: 159.65.60.245
    port: 5432
    env:
      clear:
        POSTGRES_USER: resolute-app
        POSTGRES_DB: resolute
      secret:
        - POSTGRES_PASSWORD
    files:
      - config/init.sql:/docker-entrypoint-initdb.d/setup.sql
    directories:
      - data:/var/lib/postgresql/data
